# Generated by Django 4.2.7 on 2023-11-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumbre',
            new_name='phonenumber',
        ),
    ]
