# Generated by Django 4.2.7 on 2023-11-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='Nombre',
        ),
    ]
