# Generated by Django 4.2.7 on 2023-11-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_name_trainer_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Adderss',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='DOB',
            new_name='FechaNacimiento',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Fullname',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Gender',
            new_name='NombreCompleto',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Reference',
            new_name='Referencia',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectTrainer',
            new_name='SeleccionarEntrenador',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectMemberShipplan',
            new_name='SeleccionarMembresia',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='timeStamp',
            new_name='SelloDeTiempo',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='PhoneNumber',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='membershipplan',
            old_name='plan',
            new_name='Plan',
        ),
        migrations.RenameField(
            model_name='membershipplan',
            old_name='price',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='gender',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='salary',
            new_name='Salario',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='timeStamp',
            new_name='SelloDeTiempo',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='phone',
            new_name='Telefono',
        ),
    ]
