# Generated by Django 4.2.7 on 2023-11-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_description_contact_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacto',
        ),
        migrations.RenameModel(
            old_name='Trainer',
            new_name='Entrenadores',
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Inscripcion',
        ),
        migrations.RenameModel(
            old_name='MembershipPlan',
            new_name='Membresias',
        ),
    ]
