# Generated by Django 4.2.7 on 2023-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_rename_contact_contacto_rename_trainer_entrenadores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrenadores',
            new_name='Entrenadore',
        ),
        migrations.RenameModel(
            old_name='Inscripcion',
            new_name='Inscripcione',
        ),
        migrations.RenameModel(
            old_name='Membresias',
            new_name='Membresia',
        ),
    ]
