# Generated by Django 4.2.7 on 2023-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_rename_entrenadores_entrenadore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcione',
            name='EstadoDePago',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='inscripcione',
            name='FechaVencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcione',
            name='Precio',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
