# Generated by Django 4.2.7 on 2023-11-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_inscripcione_estadodepago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcione',
            name='Cedula',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
