# Generated by Django 4.2.7 on 2023-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_rename_inscripcione_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Referencia',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Cedula',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
