# Generated by Django 4.2.7 on 2024-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_remove_usuario_referencia_alter_usuario_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('InicioSesion', models.CharField(max_length=200)),
                ('FinSesion', models.CharField(max_length=200)),
                ('Entrenamiento', models.CharField(max_length=200)),
                ('Entrenador', models.CharField(max_length=200)),
            ],
        ),
    ]
