# Generated by Django 4.2.7 on 2024-01-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='Telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
