# Generated by Django 4.2.7 on 2024-01-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_asistencia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='Entrenador',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='Telefono',
        ),
    ]
