# Generated by Django 4.2.7 on 2024-01-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_rename_usuario_asistencia_nombrecompleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='NombreCompleto',
            new_name='Usuario',
        ),
    ]
