# Generated by Django 4.2.7 on 2024-01-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_rename_nombrecompleto_asistencia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Genero',
        ),
    ]
