# Generated by Django 4.2.7 on 2024-01-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_remove_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='Fecha',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
