# Generated by Django 4.2.7 on 2024-01-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
