# Generated by Django 4.2.7 on 2024-05-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_contacto_dos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto_dos',
        ),
    ]
